<a href="https://colab.research.google.com/github/DilakshanMadhusanka/NLP__/blob/main/bow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("spam.csv")

df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df["spam"] = df["Category"].apply(lambda x: 1 if x == "spam" else 0)

df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

X_train, X_train.shape

(848     I am in office:)whats the matter..msg me now.i...
 1903             My sister got placed in birla soft da:-)
 449            LOL ... Have you made plans for new years?
 4225    Double eviction this week - Spiral and Michael...
 2628    I know I'm lacking on most of this particular ...
                               ...                        
 4665                      Mum not going robinson already.
 4056    When is school starting. Where will you stay. ...
 1529                 Hey what happen de. Are you alright.
 2185    I know a few people I can hit up and fuck to t...
 4090    How are you, my Love ? Are you with your broth...
 Name: Message, Length: 4457, dtype: object,
 (4457,))

In [ ]:
X_test, X_test.shape

(5203                              Me fine..absolutly fine
 3379                             Hows that watch resizing
 111              What is the plural of the noun research?
 2693    Urgent Urgent! We have 800 FREE flights to Eur...
 534                                       I'll be late...
                               ...                        
 1402    Kaiez... Enjoy ur tuition... Gee... Thk e seco...
 3775                                Ok... But bag again..
 4226    The world suffers a lot... Not because of the ...
 1417              No..few hours before.went to hair cut .
 3952               Hi dude hw r u da realy mising u today
 Name: Message, Length: 1115, dtype: object,
 (1115,))

In [ ]:
y_test

5203    0
3379    0
111     0
2693    1
534     0
       ..
1402    0
3775    0
4226    0
1417    0
3952    0
Name: spam, Length: 1115, dtype: int64

In [ ]:
y_train,y_train.shape

(848     0
 1903    0
 449     0
 4225    0
 2628    0
        ..
 4665    0
 4056    0
 1529    0
 2185    0
 4090    0
 Name: spam, Length: 4457, dtype: int64,
 (4457,))

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
type(X_test)

pandas.core.series.Series

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59378 stored elements and shape (4457, 7829)>

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7829))

In [ ]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zouk', 'èn', 'ú1'],
      shape=(7829,), dtype=object)

In [ ]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr

In [ ]:
v.vocabulary_

{'am': 948,
 'in': 3670,
 'office': 4956,
 'whats': 7563,
 'the': 6894,
 'matter': 4436,
 'msg': 4661,
 'me': 4454,
 'now': 4892,
 'will': 7606,
 'call': 1620,
 'you': 7792,
 'at': 1130,
 'break': 1502,
 'my': 4713,
 'sister': 6261,
 'got': 3231,
 'placed': 5289,
 'birla': 1370,
 'soft': 6363,
 'da': 2164,
 'lol': 4230,
 'have': 3387,
 'made': 4350,
 'plans': 5298,
 'for': 2963,
 'new': 4809,
 'years': 7768,
 'double': 2440,
 'eviction': 2700,
 'this': 6936,
 'week': 7523,
 'spiral': 6460,
 'and': 974,
 'michael': 4514,
 'good': 3213,
 'riddance': 5853,
 'to': 7017,
 'them': 6903,
 'know': 3997,
 'lacking': 4030,
 'on': 4989,
 'most': 4637,
 'of': 4945,
 'particular': 5153,
 'dramastorm': 2458,
 'details': 2292,
 'but': 1589,
 'part': 5151,
 'not': 4881,
 'worried': 7689,
 'about': 767,
 'that': 6892,
 'were': 7547,
 'trying': 7148,
 'find': 2875,
 'chinese': 1813,
 'food': 2953,
 'place': 5288,
 'around': 1085,
 'here': 3445,
 'yo': 7788,
 'game': 3096,
 'almost': 933,
 'over': 5080,


In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7829,))

In [ ]:
np.where(X_train_np[0] != 0)

(array([ 948, 1130, 1502, 1620, 3670, 4436, 4454, 4661, 4892, 4956, 6894,
        7563, 7606, 7792]),)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       974
           1       0.99      0.94      0.96       141

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       974
           1       0.99      0.94      0.96       141

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

